services:
  # YugabyteDB for development
  yugabytedb:
    image: yugabytedb/yugabyte:latest
    ports:
      - "5433:5433"   # YSQL
      - "7000:7000"   # Master UI
    volumes:
      - yugabyte_data:/home/yugabyte/yb_data
    environment:
      - YB_MASTER_ARGS=--replication_factor=1
    command: bin/yugabyted start --daemon=false
    healthcheck:
      # Relaxed healthcheck to give more time for initialization
      test: ["CMD-SHELL", "bin/yugabyted status || exit 0"]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s

  # Go API service - Using development mode
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_HOST=yugabytedb
      - DB_PORT=5433
      - DB_USER=yugabyte
      - DB_PASSWORD=yugabyte
      - DB_NAME=wave
      - JWT_SECRET=development_secret_key_replace_in_production
      - PORT=8080
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    depends_on:
      - yugabytedb
    # Override the Dockerfile's ENTRYPOINT with a development command
    entrypoint: ["go", "run", "cmd/api/main.go"]
    working_dir: /app

volumes:
  yugabyte_data: