services:
  # YugabyteDB for development
  yugabytedb:
    image: yugabytedb/yugabyte:latest
    ports:
      - "5433:5433"   # YSQL
      - "7000:7000"   # Master UI
    volumes:
      - yugabyte_data:/home/yugabyte/yb_data
    environment:
      - YB_MASTER_ARGS=--replication_factor=1
    command: bin/yugabyted start --daemon=false
    healthcheck:
      test: ["CMD-SHELL", "bin/yugabyted status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Database initialization service - FIX THE PORT HERE
  db-init:
    build: .
    volumes:
      - .:/app
    environment:
      - DB_HOST=yugabytedb
      - DB_PORT=5433
      - DB_USER=yugabyte
      - DB_PASSWORD=yugabyte
    depends_on:
      yugabytedb:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Creating wave database...' &&
        PGPASSWORD=yugabyte psql -h yugabytedb -p 5433 -U yugabyte -c 'CREATE DATABASE wave;' &&
        echo 'Database created successfully'
      "

  # Go API service
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_HOST=yugabytedb
      - DB_PORT=5433
      - DB_USER=yugabyte
      - DB_PASSWORD=yugabyte
      - DB_NAME=wave
      - JWT_SECRET=development_secret_key_replace_in_production
      - PORT=8080
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: >
      sh -c "
        echo 'Running migrations...' &&
        sleep 5 &&
        echo 'Starting API server...' &&
        go run cmd/api/main.go
      "

volumes:
  yugabyte_data: