services:
  # YugabyteDB for development
  yugabytedb:
    image: yugabytedb/yugabyte:latest
    ports:
      - "5433:5433"   # YSQL
      - "7000:7000"   # Master UI
    volumes:
      - yugabyte_data:/home/yugabyte/yb_data
    environment:
      - YB_MASTER_ARGS=--replication_factor=1
    command: bin/yugabyted start --daemon=false
    healthcheck:
      test: ["CMD-SHELL", "bin/yugabyted status && echo 'YugabyteDB is healthy' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Go API service
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_HOST=yugabytedb
      - DB_PORT=5433
      - DB_USER=yugabyte
      - DB_PASSWORD=yugabyte
      - DB_NAME=wave
      - JWT_SECRET=development_secret_key_replace_in_production
      - PORT=8080
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    depends_on:
      yugabytedb:
        condition: service_healthy
    # Add a wait script to give YugabyteDB extra time
    command: >
      sh -c "
      echo 'Waiting for YugabyteDB to be ready...' &&
      sleep 10 &&
      echo 'Starting API server...' &&
      go run cmd/api/main.go
      "

volumes:
  yugabyte_data: